// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using To_Do_App.Data;

#nullable disable

namespace To_Do_App.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("To_Do_App.Models.Todo", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Title");

                    b.ToTable("Todo");

                    b.HasData(
                        new
                        {
                            Title = "Go to church",
                            IsCompleted = true
                        },
                        new
                        {
                            Title = "Barbing",
                            IsCompleted = false
                        },
                        new
                        {
                            Title = "Meeting",
                            IsCompleted = true
                        },
                        new
                        {
                            Title = "Shopping",
                            IsCompleted = false
                        },
                        new
                        {
                            Title = "Exercise",
                            IsCompleted = false
                        },
                        new
                        {
                            Title = "Assignment",
                            IsCompleted = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
